// Generated by tool/fonts/build.mjs from Lucide 1.49.0; don't edit.
import 'package:flutter/widgets.dart';

/// The line icons of the mockups (lucide.dev), from the bundled Lucide subset.
abstract final class AppIcons {
  /// circle-alert
  static const IconData alert = IconData(0xe077, fontFamily: 'Lucide');
  /// arrow-left
  static const IconData back = IconData(0xe048, fontFamily: 'Lucide');
  /// camera
  static const IconData camera = IconData(0xe064, fontFamily: 'Lucide');
  /// check
  static const IconData check = IconData(0xe06c, fontFamily: 'Lucide');
  /// circle-check
  static const IconData checkCircle = IconData(0xe226, fontFamily: 'Lucide');
  /// chevron-right
  static const IconData chevronRight = IconData(0xe06f, fontFamily: 'Lucide');
  /// circle
  static const IconData circle = IconData(0xe076, fontFamily: 'Lucide');
  /// clipboard-paste
  static const IconData clipboard = IconData(0xe3e8, fontFamily: 'Lucide');
  /// clock
  static const IconData clock = IconData(0xe087, fontFamily: 'Lucide');
  /// cloud
  static const IconData cloud = IconData(0xe088, fontFamily: 'Lucide');
  /// crown
  static const IconData crown = IconData(0xe1d6, fontFamily: 'Lucide');
  /// download
  static const IconData download = IconData(0xe0b2, fontFamily: 'Lucide');
  /// eye
  static const IconData eye = IconData(0xe0ba, fontFamily: 'Lucide');
  /// eye-off
  static const IconData eyeOff = IconData(0xe0bb, fontFamily: 'Lucide');
  /// file
  static const IconData file = IconData(0xe0c0, fontFamily: 'Lucide');
  /// file-text
  static const IconData fileText = IconData(0xe0cc, fontFamily: 'Lucide');
  /// folder
  static const IconData folder = IconData(0xe0d7, fontFamily: 'Lucide');
  /// globe
  static const IconData globe = IconData(0xe0e8, fontFamily: 'Lucide');
  /// hard-drive
  static const IconData hardDrive = IconData(0xe0ed, fontFamily: 'Lucide');
  /// house
  static const IconData home = IconData(0xe0f5, fontFamily: 'Lucide');
  /// hourglass
  static const IconData hourglass = IconData(0xe296, fontFamily: 'Lucide');
  /// image
  static const IconData image = IconData(0xe0f6, fontFamily: 'Lucide');
  /// images
  static const IconData images = IconData(0xe5c4, fontFamily: 'Lucide');
  /// infinity
  static const IconData infinity = IconData(0xe1e7, fontFamily: 'Lucide');
  /// info
  static const IconData info = IconData(0xe0f9, fontFamily: 'Lucide');
  /// key-round
  static const IconData key = IconData(0xe4a3, fontFamily: 'Lucide');
  /// languages
  static const IconData languages = IconData(0xe0fe, fontFamily: 'Lucide');
  /// lock
  static const IconData lock = IconData(0xe10b, fontFamily: 'Lucide');
  /// lock-open
  static const IconData lockOpen = IconData(0xe10c, fontFamily: 'Lucide');
  /// log-out
  static const IconData logOut = IconData(0xe10e, fontFamily: 'Lucide');
  /// minus
  static const IconData minus = IconData(0xe11c, fontFamily: 'Lucide');
  /// circle-minus
  static const IconData minusCircle = IconData(0xe07e, fontFamily: 'Lucide');
  /// ellipsis-vertical
  static const IconData more = IconData(0xe0b7, fontFamily: 'Lucide');
  /// play
  static const IconData play = IconData(0xe13c, fontFamily: 'Lucide');
  /// circle-play
  static const IconData playCircle = IconData(0xe080, fontFamily: 'Lucide');
  /// plus
  static const IconData plus = IconData(0xe13d, fontFamily: 'Lucide');
  /// qr-code
  static const IconData qrCode = IconData(0xe1df, fontFamily: 'Lucide');
  /// refresh-cw
  static const IconData refresh = IconData(0xe145, fontFamily: 'Lucide');
  /// rotate-ccw
  static const IconData rotate = IconData(0xe148, fontFamily: 'Lucide');
  /// scan-qr-code
  static const IconData scan = IconData(0xe5f6, fontFamily: 'Lucide');
  /// search
  static const IconData search = IconData(0xe151, fontFamily: 'Lucide');
  /// server
  static const IconData server = IconData(0xe153, fontFamily: 'Lucide');
  /// settings
  static const IconData settings = IconData(0xe154, fontFamily: 'Lucide');
  /// share-2
  static const IconData share = IconData(0xe156, fontFamily: 'Lucide');
  /// shield
  static const IconData shield = IconData(0xe158, fontFamily: 'Lucide');
  /// smartphone
  static const IconData smartphone = IconData(0xe163, fontFamily: 'Lucide');
  /// trash-2
  static const IconData trash = IconData(0xe18e, fontFamily: 'Lucide');
  /// undo-2
  static const IconData undo = IconData(0xe2a1, fontFamily: 'Lucide');
  /// upload
  static const IconData upload = IconData(0xe19e, fontFamily: 'Lucide');
  /// user
  static const IconData user = IconData(0xe19f, fontFamily: 'Lucide');
  /// user-plus
  static const IconData userPlus = IconData(0xe1a2, fontFamily: 'Lucide');
  /// user-x
  static const IconData userX = IconData(0xe1a3, fontFamily: 'Lucide');
  /// video
  static const IconData video = IconData(0xe1a5, fontFamily: 'Lucide');
  /// wifi
  static const IconData wifi = IconData(0xe1ae, fontFamily: 'Lucide');
  /// wifi-off
  static const IconData wifiOff = IconData(0xe1af, fontFamily: 'Lucide');
  /// x
  static const IconData x = IconData(0xe1b2, fontFamily: 'Lucide');
}
