include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/l10n/app_localizations*.dart
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    - prefer_single_quotes
    - prefer_final_locals
    - unawaited_futures
    - always_declare_return_types
