// Builds the app's bundled fonts and lib/ui/icons.dart. Run once after changing the icon
// list (npm install && npm run icons in app/tool; npm run fonts also makes the text fonts
// again); the output is committed, so building the app never needs the network.
//
// - Noto Serif Bold for headings, Roboto Mono SemiBold for PINs and paths: the variable
//   fonts from Google Fonts, pinned to the one weight the app uses and cut down to Latin.
//   Body text is Roboto, which Android has.
// - Lucide icons, as in the mockups: only the icons listed below.
import { mkdir, writeFile } from 'node:fs/promises';
import subsetFont from 'subset-font';

const lucideVersion = '1.49.0';
const out = new URL('../../assets/fonts/', import.meta.url);
const dartOut = new URL('../../lib/ui/icons.dart', import.meta.url);

// Dart name → Lucide name. Keep in step with the mockups' icons.
const icons = {
  alert: 'circle-alert',
  back: 'arrow-left',
  camera: 'camera',
  check: 'check',
  checkCircle: 'circle-check',
  chevronRight: 'chevron-right',
  circle: 'circle',
  clipboard: 'clipboard-paste',
  clock: 'clock',
  cloud: 'cloud',
  crown: 'crown',
  download: 'download',
  eye: 'eye',
  eyeOff: 'eye-off',
  file: 'file',
  fileText: 'file-text',
  folder: 'folder',
  globe: 'globe',
  hardDrive: 'hard-drive',
  home: 'house',
  hourglass: 'hourglass',
  image: 'image',
  images: 'images',
  infinity: 'infinity',
  info: 'info',
  key: 'key-round',
  languages: 'languages',
  lock: 'lock',
  lockOpen: 'lock-open',
  logOut: 'log-out',
  minus: 'minus',
  minusCircle: 'circle-minus',
  more: 'ellipsis-vertical',
  palette: 'palette',
  play: 'play',
  playCircle: 'circle-play',
  plus: 'plus',
  qrCode: 'qr-code',
  refresh: 'refresh-cw',
  rotate: 'rotate-ccw',
  scan: 'scan-qr-code',
  search: 'search',
  server: 'server',
  settings: 'settings',
  share: 'share-2',
  shield: 'shield',
  smartphone: 'smartphone',
  trash: 'trash-2',
  undo: 'undo-2',
  upload: 'upload',
  user: 'user',
  userPlus: 'user-plus',
  userX: 'user-x',
  video: 'video',
  wifi: 'wifi',
  wifiOff: 'wifi-off',
  x: 'x',
};

async function get(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

const range = (from, to) => Array.from({ length: to - from + 1 }, (_, i) => String.fromCodePoint(from + i)).join('');
// ASCII, Latin-1, Latin Extended-A, typographic punctuation, euro, trade mark.
const latin = range(0x20, 0x7e) + range(0xa0, 0x17f) + range(0x2010, 0x2027) + range(0x2030, 0x203a) + '€™';

const googleFonts = 'https://raw.githubusercontent.com/google/fonts/main/ofl';
await mkdir(out, { recursive: true });
// --icons-only keeps the text fonts as they are: Google Fonts' main branch may have moved on.
const textFonts = !process.argv.includes('--icons-only');

if (textFonts) {
  const serif = await get(`${googleFonts}/notoserif/NotoSerif%5Bwdth,wght%5D.ttf`);
  await writeFile(new URL('NotoSerif-Bold.ttf', out),
    await subsetFont(serif, latin, { targetFormat: 'truetype', variationAxes: { wght: 700, wdth: 100 } }));
  await writeFile(new URL('OFL-NotoSerif.txt', out), await get(`${googleFonts}/notoserif/OFL.txt`));

  const mono = await get(`${googleFonts}/robotomono/RobotoMono%5Bwght%5D.ttf`);
  await writeFile(new URL('RobotoMono-SemiBold.ttf', out),
    await subsetFont(mono, range(0x20, 0x7e) + range(0xa0, 0xff), { targetFormat: 'truetype', variationAxes: { wght: 600 } }));
  await writeFile(new URL('OFL-RobotoMono.txt', out), await get(`${googleFonts}/robotomono/OFL.txt`));
}

const cdn = `https://cdn.jsdelivr.net/npm/lucide-static@${lucideVersion}`;
const codepoints = JSON.parse((await get(`${cdn}/font/codepoints.json`)).toString());
const missing = Object.values(icons).filter((n) => !(n in codepoints));
if (missing.length) throw new Error(`not in Lucide ${lucideVersion}: ${missing.join(', ')}`);
const glyphs = Object.values(icons).map((n) => String.fromCodePoint(codepoints[n])).join('');
await writeFile(new URL('Lucide.ttf', out), await subsetFont(await get(`${cdn}/font/lucide.ttf`), glyphs, { targetFormat: 'truetype' }));
await writeFile(new URL('LICENSE-Lucide.txt', out), await get(`${cdn}/LICENSE`));

const dart = `// Generated by tool/fonts/build.mjs from Lucide ${lucideVersion}; don't edit.
import 'package:flutter/widgets.dart';

/// The line icons of the mockups (lucide.dev), from the bundled Lucide subset.
abstract final class AppIcons {
${Object.entries(icons)
  .map(([dartName, name]) => `  /// ${name}\n  static const IconData ${dartName} = IconData(0x${codepoints[name].toString(16)}, fontFamily: 'Lucide');`)
  .join('\n')}
}
`;
await writeFile(dartOut, dart);
console.log(`fonts and ${Object.keys(icons).length} icons written`);
